// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: comdex/liquidation/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LockedVaultInfo struct {
	LockedVaultId          uint64                                 `protobuf:"varint,1,opt,name=locked_vault_id,json=lockedVaultId,proto3" json:"locked_vault_id,omitempty"`
	Id                     uint64                                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	PairID                 uint64                                 `protobuf:"varint,3,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty" yaml:"pair_id"`
	Owner                  string                                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner"`
	Collateral             types.Coin                             `protobuf:"bytes,5,opt,name=collateral,proto3" json:"collateral" yaml:"collateral"`
	Debt                   types.Coin                             `protobuf:"bytes,6,opt,name=debt,proto3" json:"debt" yaml:"debt"`
	CollateralizationRatio github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,7,opt,name=collateralization_ratio,json=collateralizationRatio,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"collateralization_ratio" yaml:"collateralization_ratio"`
	NewOwner               string                                 `protobuf:"bytes,8,opt,name=new_owner,json=newOwner,proto3" json:"new_owner,omitempty" yaml:"admin"`
}

func (m *LockedVaultInfo) Reset()         { *m = LockedVaultInfo{} }
func (m *LockedVaultInfo) String() string { return proto.CompactTextString(m) }
func (*LockedVaultInfo) ProtoMessage()    {}
func (*LockedVaultInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_66cac120b864d78b, []int{0}
}
func (m *LockedVaultInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LockedVaultInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LockedVaultInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LockedVaultInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockedVaultInfo.Merge(m, src)
}
func (m *LockedVaultInfo) XXX_Size() int {
	return m.Size()
}
func (m *LockedVaultInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LockedVaultInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LockedVaultInfo proto.InternalMessageInfo

func (m *LockedVaultInfo) GetLockedVaultId() uint64 {
	if m != nil {
		return m.LockedVaultId
	}
	return 0
}

func (m *LockedVaultInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LockedVaultInfo) GetPairID() uint64 {
	if m != nil {
		return m.PairID
	}
	return 0
}

func (m *LockedVaultInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *LockedVaultInfo) GetCollateral() types.Coin {
	if m != nil {
		return m.Collateral
	}
	return types.Coin{}
}

func (m *LockedVaultInfo) GetDebt() types.Coin {
	if m != nil {
		return m.Debt
	}
	return types.Coin{}
}

func (m *LockedVaultInfo) GetNewOwner() string {
	if m != nil {
		return m.NewOwner
	}
	return ""
}

type QueryLockedVaultRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id"`
}

func (m *QueryLockedVaultRequest) Reset()         { *m = QueryLockedVaultRequest{} }
func (m *QueryLockedVaultRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLockedVaultRequest) ProtoMessage()    {}
func (*QueryLockedVaultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66cac120b864d78b, []int{1}
}
func (m *QueryLockedVaultRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLockedVaultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLockedVaultRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLockedVaultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLockedVaultRequest.Merge(m, src)
}
func (m *QueryLockedVaultRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLockedVaultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLockedVaultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLockedVaultRequest proto.InternalMessageInfo

func (m *QueryLockedVaultRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryLockedVaultResponse struct {
	LockedVaultInfo LockedVaultInfo `protobuf:"bytes,1,opt,name=LockedVaultInfo,proto3" json:"LockedVaultInfo" yaml:"vaultInfo"`
}

func (m *QueryLockedVaultResponse) Reset()         { *m = QueryLockedVaultResponse{} }
func (m *QueryLockedVaultResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLockedVaultResponse) ProtoMessage()    {}
func (*QueryLockedVaultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66cac120b864d78b, []int{2}
}
func (m *QueryLockedVaultResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLockedVaultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLockedVaultResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLockedVaultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLockedVaultResponse.Merge(m, src)
}
func (m *QueryLockedVaultResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLockedVaultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLockedVaultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLockedVaultResponse proto.InternalMessageInfo

func (m *QueryLockedVaultResponse) GetLockedVaultInfo() LockedVaultInfo {
	if m != nil {
		return m.LockedVaultInfo
	}
	return LockedVaultInfo{}
}

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66cac120b864d78b, []int{3}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66cac120b864d78b, []int{4}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func init() {
	proto.RegisterType((*LockedVaultInfo)(nil), "comdex.liquidation.v1beta1.LockedVaultInfo")
	proto.RegisterType((*QueryLockedVaultRequest)(nil), "comdex.liquidation.v1beta1.QueryLockedVaultRequest")
	proto.RegisterType((*QueryLockedVaultResponse)(nil), "comdex.liquidation.v1beta1.QueryLockedVaultResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "comdex.liquidation.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "comdex.liquidation.v1beta1.QueryParamsResponse")
}

func init() {
	proto.RegisterFile("comdex/liquidation/v1beta1/query.proto", fileDescriptor_66cac120b864d78b)
}

var fileDescriptor_66cac120b864d78b = []byte{
	// 696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcf, 0x4f, 0xd4, 0x40,
	0x14, 0xde, 0x2e, 0xcb, 0x02, 0x83, 0xfc, 0x70, 0x20, 0x52, 0x36, 0xd8, 0x92, 0x89, 0x59, 0x09,
	0x84, 0x56, 0x40, 0x8c, 0xf1, 0x64, 0x2a, 0x17, 0x12, 0x13, 0xb0, 0x31, 0x9a, 0x78, 0xd9, 0xcc,
	0x76, 0x86, 0x75, 0x42, 0xb7, 0x53, 0xda, 0x2e, 0x88, 0xc6, 0x0b, 0x37, 0x6f, 0x26, 0xc6, 0xb3,
	0x7f, 0x85, 0xff, 0x03, 0x47, 0x12, 0x0f, 0x1a, 0x0f, 0x8d, 0x59, 0xfc, 0x0b, 0xf6, 0x6e, 0x62,
	0x66, 0xa6, 0x2b, 0xfb, 0x23, 0xee, 0xea, 0xa5, 0x9d, 0xbc, 0xf9, 0xbe, 0xef, 0x7d, 0xf3, 0xde,
	0xbc, 0x01, 0x65, 0x8f, 0xd7, 0x09, 0x7d, 0x65, 0xfb, 0xec, 0xa8, 0xc1, 0x08, 0x4e, 0x18, 0x0f,
	0xec, 0xe3, 0x8d, 0x2a, 0x4d, 0xf0, 0x86, 0x7d, 0xd4, 0xa0, 0xd1, 0xa9, 0x15, 0x46, 0x3c, 0xe1,
	0xb0, 0xa4, 0x70, 0x56, 0x07, 0xce, 0xca, 0x70, 0xa5, 0xf9, 0x1a, 0xaf, 0x71, 0x09, 0xb3, 0xc5,
	0x4a, 0x31, 0x4a, 0x4b, 0x35, 0xce, 0x6b, 0x3e, 0xb5, 0x71, 0xc8, 0x6c, 0x1c, 0x04, 0x3c, 0x91,
	0xa4, 0x38, 0xdb, 0x5d, 0xf5, 0x78, 0x5c, 0xe7, 0xb1, 0x5d, 0xc5, 0x31, 0x55, 0x89, 0xfe, 0xa4,
	0x0d, 0x71, 0x8d, 0x05, 0x2a, 0x83, 0xc2, 0xde, 0x1e, 0xe0, 0x31, 0xc4, 0x11, 0xae, 0xb7, 0x45,
	0x8d, 0x4e, 0xd1, 0x36, 0xc2, 0xe3, 0x2c, 0x13, 0x42, 0xbf, 0x46, 0xc0, 0xcc, 0x63, 0xee, 0x1d,
	0x52, 0xf2, 0x0c, 0x37, 0xfc, 0x64, 0x37, 0x38, 0xe0, 0xb0, 0x0c, 0x66, 0x7c, 0x19, 0xaa, 0x1c,
	0x8b, 0x58, 0x85, 0x11, 0x5d, 0x5b, 0xd6, 0x56, 0x0a, 0xee, 0x94, 0xdf, 0x81, 0x24, 0x70, 0x1a,
	0xe4, 0x19, 0xd1, 0xf3, 0x72, 0x2b, 0xcf, 0x08, 0xdc, 0x06, 0x63, 0x21, 0x66, 0x91, 0xc0, 0x8f,
	0x88, 0xa0, 0xb3, 0xd4, 0x4c, 0xcd, 0xe2, 0x3e, 0x66, 0xd1, 0xee, 0x4e, 0x2b, 0x35, 0xa7, 0x4f,
	0x71, 0xdd, 0x7f, 0x80, 0x32, 0x08, 0x72, 0x8b, 0x62, 0xb5, 0x4b, 0x60, 0x19, 0x8c, 0xf2, 0x93,
	0x80, 0x46, 0x7a, 0x61, 0x59, 0x5b, 0x99, 0x70, 0x66, 0x5b, 0xa9, 0x79, 0x4d, 0x41, 0x65, 0x18,
	0xb9, 0x6a, 0x1b, 0x3e, 0x05, 0xc0, 0xe3, 0xbe, 0x8f, 0x13, 0x1a, 0x61, 0x5f, 0x1f, 0x5d, 0xd6,
	0x56, 0x26, 0x37, 0x17, 0x2d, 0x75, 0x3e, 0x4b, 0x9c, 0xaf, 0x5d, 0x7d, 0xeb, 0x11, 0x67, 0x81,
	0xb3, 0x78, 0x9e, 0x9a, 0xb9, 0x56, 0x6a, 0x5e, 0x57, 0x5a, 0x57, 0x54, 0xe4, 0x76, 0xe8, 0x40,
	0x07, 0x14, 0x08, 0xad, 0x26, 0x7a, 0x71, 0x98, 0xde, 0x5c, 0xa6, 0x37, 0xa9, 0xf4, 0x04, 0x09,
	0xb9, 0x92, 0x0b, 0xdf, 0x69, 0x60, 0xe1, 0x4a, 0x92, 0xbd, 0x96, 0xfd, 0xa8, 0x44, 0xe2, 0xa7,
	0x8f, 0xc9, 0x43, 0xed, 0x0b, 0xf2, 0xf7, 0xd4, 0x2c, 0xd7, 0x58, 0xf2, 0xb2, 0x51, 0xb5, 0x3c,
	0x5e, 0xb7, 0xb3, 0xce, 0xa8, 0xdf, 0x7a, 0x4c, 0x0e, 0xed, 0xe4, 0x34, 0xa4, 0xb1, 0xb5, 0x43,
	0xbd, 0x56, 0x6a, 0x1a, 0xbd, 0xb6, 0xbb, 0x64, 0x91, 0x7b, 0xa3, 0x6f, 0xc7, 0x15, 0x5f, 0xb8,
	0x0e, 0x26, 0x02, 0x7a, 0x52, 0x51, 0x15, 0x1d, 0xef, 0xad, 0x28, 0x26, 0x75, 0x16, 0x20, 0x77,
	0x3c, 0xa0, 0x27, 0x7b, 0xb2, 0xb8, 0xf7, 0xc1, 0xc2, 0x13, 0x71, 0xd5, 0x3a, 0xee, 0x80, 0x4b,
	0x8f, 0x1a, 0x34, 0x4e, 0xe0, 0x4d, 0xd9, 0x5e, 0xd9, 0x79, 0x67, 0xaa, 0x95, 0x9a, 0x13, 0x4a,
	0x42, 0xb4, 0x2e, 0xcf, 0x08, 0xfa, 0xa4, 0x01, 0xbd, 0x9f, 0x1a, 0x87, 0x3c, 0x88, 0x29, 0x3c,
	0xd3, 0xfa, 0xae, 0x95, 0x54, 0x9a, 0xdc, 0x5c, 0xb3, 0xfe, 0x3e, 0x36, 0x56, 0x0f, 0xc5, 0x59,
	0x13, 0x65, 0x6b, 0xa6, 0x66, 0xaf, 0x56, 0x2b, 0x35, 0x67, 0x95, 0x9b, 0xe3, 0x76, 0x08, 0xb9,
	0xbd, 0x20, 0x34, 0x0f, 0xa0, 0x34, 0xb8, 0x2f, 0x07, 0x22, 0x3b, 0x16, 0x7a, 0x0e, 0xe6, 0xba,
	0xa2, 0x99, 0xe3, 0x87, 0xa0, 0xa8, 0x06, 0x27, 0xf3, 0x89, 0x06, 0xf9, 0x54, 0x5c, 0xa7, 0x20,
	0xec, 0xb9, 0x19, 0x6f, 0xf3, 0x6b, 0x1e, 0x8c, 0x4a, 0x65, 0xf8, 0x51, 0x03, 0x45, 0x05, 0x81,
	0xd6, 0x20, 0x99, 0x7e, 0x77, 0x25, 0xfb, 0x9f, 0xf1, 0xca, 0x37, 0x5a, 0x3d, 0xfb, 0xf2, 0xf3,
	0x43, 0xfe, 0x16, 0x44, 0xf6, 0xd0, 0x27, 0x01, 0x7e, 0xd6, 0xc0, 0x6c, 0x6f, 0xcb, 0xe0, 0xd6,
	0xd0, 0x8c, 0xfd, 0x77, 0xa3, 0x74, 0xf7, 0xff, 0x48, 0x99, 0xd7, 0x7b, 0xd2, 0xeb, 0x1d, 0x68,
	0x0d, 0xf2, 0xda, 0xf9, 0xf4, 0xc4, 0xf6, 0x1b, 0x46, 0xde, 0x3a, 0x7b, 0xe7, 0x4d, 0x43, 0xbb,
	0x68, 0x1a, 0xda, 0x8f, 0xa6, 0xa1, 0xbd, 0xbf, 0x34, 0x72, 0x17, 0x97, 0x46, 0xee, 0xdb, 0xa5,
	0x91, 0x7b, 0xb1, 0xdd, 0x35, 0x4f, 0x42, 0x73, 0x9d, 0x1f, 0x1c, 0x30, 0x8f, 0x61, 0xbf, 0x9d,
	0xa3, 0x3b, 0x8b, 0x1c, 0xb1, 0x6a, 0x51, 0x3e, 0x7e, 0x5b, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xcf, 0x0c, 0x1d, 0x04, 0xeb, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	QueryLockedVault(ctx context.Context, in *QueryLockedVaultRequest, opts ...grpc.CallOption) (*QueryLockedVaultResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/comdex.liquidation.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryLockedVault(ctx context.Context, in *QueryLockedVaultRequest, opts ...grpc.CallOption) (*QueryLockedVaultResponse, error) {
	out := new(QueryLockedVaultResponse)
	err := c.cc.Invoke(ctx, "/comdex.liquidation.v1beta1.Query/QueryLockedVault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	QueryLockedVault(context.Context, *QueryLockedVaultRequest) (*QueryLockedVaultResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) QueryLockedVault(ctx context.Context, req *QueryLockedVaultRequest) (*QueryLockedVaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLockedVault not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comdex.liquidation.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryLockedVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLockedVaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryLockedVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comdex.liquidation.v1beta1.Query/QueryLockedVault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryLockedVault(ctx, req.(*QueryLockedVaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "comdex.liquidation.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "QueryLockedVault",
			Handler:    _Query_QueryLockedVault_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comdex/liquidation/v1beta1/query.proto",
}

func (m *LockedVaultInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LockedVaultInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LockedVaultInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewOwner) > 0 {
		i -= len(m.NewOwner)
		copy(dAtA[i:], m.NewOwner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.NewOwner)))
		i--
		dAtA[i] = 0x42
	}
	{
		size := m.CollateralizationRatio.Size()
		i -= size
		if _, err := m.CollateralizationRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.Debt.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.Collateral.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x22
	}
	if m.PairID != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PairID))
		i--
		dAtA[i] = 0x18
	}
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if m.LockedVaultId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LockedVaultId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryLockedVaultRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLockedVaultRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLockedVaultRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryLockedVaultResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLockedVaultResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLockedVaultResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.LockedVaultInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LockedVaultInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LockedVaultId != 0 {
		n += 1 + sovQuery(uint64(m.LockedVaultId))
	}
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	if m.PairID != 0 {
		n += 1 + sovQuery(uint64(m.PairID))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = m.Collateral.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.Debt.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.CollateralizationRatio.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = len(m.NewOwner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLockedVaultRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryLockedVaultResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LockedVaultInfo.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LockedVaultInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LockedVaultInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LockedVaultInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedVaultId", wireType)
			}
			m.LockedVaultId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockedVaultId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PairID", wireType)
			}
			m.PairID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PairID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Collateral.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Debt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Debt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralizationRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollateralizationRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLockedVaultRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLockedVaultRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLockedVaultRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLockedVaultResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLockedVaultResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLockedVaultResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedVaultInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LockedVaultInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
